<?php

namespace AppBundle\Repository;

/**
 * ThemrubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemerubRepository extends \Doctrine\ORM\EntityRepository
{
}
