home:
    path:     /
    defaults: { _controller: AppBundle:General:index}

photo:
    path:     /{url}
    defaults: { _controller: AppBundle:General:photo}
    requirements:
        url: ^[a-z]+-[a-z]+$
  
presentation:
    path:     /presentation
    defaults: { _controller: AppBundle:General:presentation}
  
tarifs:
    path:     /tarifs
    defaults: { _controller: AppBundle:General:tarifs}
  
contact:
    path:     /contact
    defaults: { _controller: AppBundle:General:contacts}
  
livre:
    path:     /livredor
    defaults: { _controller: AppBundle:General:livre}
    
carrousel:
    path:    /carrousel
    defaults: { _controller: AppBundle:General:carrousel}
